version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 33:14:91:7f:a9:25:f4:a1:5e:cf:c0:6f:55:a1:7f:2b
      - checkout 
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
#          command: yarn install --frozen-lockfile
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Authenticate with registry
          # the npm_TOKEN should be added to CircleCI environment variables
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: yarn publish --access public